#!/usr/bin/env bash
# init script to manage 'manage_my_process'

# Start function
start() {
	bash manage_my_process &
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process started"
}

# Stop function
stop() {
	kill "$(cat /var/run/my_process.pid)"
	rm /var/run/my_process.pid
	echo "manage_my_process stopped"
}

# Restart function
restart() {
	# Stopping process
	kill "$(cat /var/run/my_process.pid)"
	rm /var/run/my_process.pid

	# Starting up process
	bash manage_my_process &
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process restarted"
}


# Main script logic
case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		exit 1
		;;
esac

exit 0
