#!/usr/bin/env bash
# fixing issues from using docker 
# make the apache sever return Hello Horberton when querying the root

echo "Restarting Nginx"
if nginx -t; then
	nginx -s restart
else
	echo "Recheck configuration"
fi
