#!/usr/bin/env bash

# Initialize a counter variable
counter=1

# Loop while counter is less than or equal to 10
while [ $counter -le 10 ]
do
    echo "Best School"
    # Increment the counter
    ((counter++))
done
