#!/usr/bin/env bash

# Initialize a counter variable
counter=1

# Loop until counter is greater than 10
until [ $counter -gt 10 ]
do
    echo "Best School"
    # Increment the counter
    ((counter++))
done
