#!/usr/bin/env bash
# Initialize a counter variable
counter=1

# Loop while counter is less than or equal to 10
while [ $counter -le 10 ]
do
    # Check if the counter is 9
    if [ $counter -eq 9 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    # Increment the counter
    ((counter++))
done

